server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: TeamService
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true