server:
  port: 8083
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: MatchService
     
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG